version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/hello
hooks:
  AfterInstall:
    - location: stopapp.sh
    - runas: ec2-user
  ApplicationStart:
    - location: runapp.sh
      runas: ec2-user
